job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: peru
    CONTAINER_PREFIX: planet4-peru
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-peru
    NEWRELIC_APPNAME: P4 Peru Development
    WP_DB_NAME: planet4-peru_wordpress_develop
    WP_STATELESS_BUCKET: planet4-peru-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: peru
    HELM_RELEASE: planet4-peru-release
    NEWRELIC_APPNAME: P4 Peru Release
    WP_DB_NAME: planet4-peru_wordpress_release
    WP_STATELESS_BUCKET: planet4-peru-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: peru
    HELM_RELEASE: planet4-peru-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Peru Production
    WP_DB_NAME: planet4-peru_wordpress_master
    WP_STATELESS_BUCKET: planet4-peru-stateless
